version: '3'

services:
  pg:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ../kalique_data/pg:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        appdir: /appdir
    environment:
      PG_HOST: pg
      BUNDLE_PATH: /bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/appdir:cached
      - ../kalique_data/bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - pg
