version: '3.4'

services:
  pg:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ../kalique_data/pg:/var/lib/postgresql/data

  app: &app
    build:
      context: .
      target: kalique_base
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    environment:
      PG_HOST: pg
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    depends_on:
      - pg

  runner:
    <<: *backend
    command: /bin/bash

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"

volumes:
  bundle:
